//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.05 at 12:15:35 PM ALMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "Chuggington", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.epam.edu.xmlobject;
